version: "3"
services:
  ackee:
    image: aleccool213/calsync
    container_name: calsync
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CALSYNC_MONGODB=mongodb://mongo:27017/calsync
    env_file:
      - .env.local
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./data:/data/db
